"""Initial migration

Revision ID: 53419044b405
Revises: 
Create Date: 2025-12-09 12:41:39.996703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53419044b405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('category', sa.Enum('NEWS', 'PUBLICATION', 'TECH', 'OTHER', name='post_category'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
